+ set -o errtrace
+ python /rds/general/user/ga402/home/009_GAN/001_2D_DBGAN/dbgan2d.py --project /rds/general/user/ga402/home/PROJECTS/001_AMLCD8TC/DBGAN2d --dataroot /rds/general/user/ga402/home/PROJECTS/001_AMLCD8TC/IMAGES2D --workers 2 --batch_size 128 --image_size 128 --nc 3 --nz 100 --ngf 64 --ndf 64 --num_epochs 5 --lr 0.0002 --beta1 0.5 --ngpu 1
[W Context.cpp:70] Warning: torch.use_deterministic_algorithms is in beta, and its design and functionality may change in the future. (function operator())
Traceback (most recent call last):
  File "/rds/general/user/ga402/home/009_GAN/001_2D_DBGAN/dbgan2d.py", line 212, in <module>
    errD_real = criterion(output, label)
  File "/rds/general/user/ga402/home/miniconda/envs/yoloV5_model/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/rds/general/user/ga402/home/miniconda/envs/yoloV5_model/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 613, in forward
    return F.binary_cross_entropy(input, target, weight=self.weight, reduction=self.reduction)
  File "/rds/general/user/ga402/home/miniconda/envs/yoloV5_model/lib/python3.6/site-packages/torch/nn/functional.py", line 2755, in binary_cross_entropy
    "Please ensure they have the same size.".format(target.size(), input.size())
ValueError: Using a target size (torch.Size([128])) that is different to the input size (torch.Size([512])) is deprecated. Please ensure they have the same size.
