+ set -o errtrace
+ python /rds/general/user/ga402/home/009_GAN/001_2D_DBGAN/dbgan2d.py --project /rds/general/user/ga402/home/PROJECTS/001_AMLCD8TC/DBGAN2d --dataroot /rds/general/user/ga402/home/PROJECTS/001_AMLCD8TC/IMAGES2D --workers 2 --batch_size 128 --image_size 128 --nc 3 --nz 100 --ngf 64 --ndf 64 --num_epochs 20 --lr 0.00001 --beta1 0.5 --ngpu 1 --accessory_info 'DBGAN2d; Wasserstein GAN attempt'
[W Context.cpp:70] Warning: torch.use_deterministic_algorithms is in beta, and its design and functionality may change in the future. (function operator())
Traceback (most recent call last):
  File "/rds/general/user/ga402/home/009_GAN/001_2D_DBGAN/dbgan2d.py", line 269, in <module>
    save_fake_images,
  File "/rds/general/user/ga402/home/009_GAN/001_2D_DBGAN/utils/wgan_utils.py", line 137, in w_fit
    gen, disc, disc_optimiser, images, batch_size, z_dim, device
  File "/rds/general/user/ga402/home/009_GAN/001_2D_DBGAN/utils/wgan_utils.py", line 64, in w_train_discriminator
    errD_fake = torch.mea(fake_score)
AttributeError: module 'torch' has no attribute 'mea'
